### ISSUE TITLE
您好，您说明里的完整脚本，并不能用啊

### ISSUE THREAD

**Issue by liyuhaolol** [angcyo/Android_Gradle_DSL_4.0#1]
```gradle
android {
    applicationVariants.all { variant ->
        if (variant.buildType.name != "debug") {
            variant.packageApplicationProvider.get().outputDirectory = rootProject.file("/apk")
        }
        variant.outputs.forEach {
            it.apkData.outputFileName = "test.apk"
        }
    }
}
```
### 这个代码在打包时会提示<Failed to create directory '/apk'>根本就不能用啊，请问gradle4.0这个版本到底怎么自定义apk打包的路径呢?

**Comment by angcyo** [comment]
我的测试环境:

`Android Studio 4.0`

`classpath "com.android.tools.build:gradle:4.0.0"`

`gradle-6.1.1-all`

`Windows 10`

**Comment by liyuhaolol** [comment]
> 我的测试环境:
> 
> `Android Studio 4.0`
> 
> `classpath "com.android.tools.build:gradle:4.0.0"`
> 
> `gradle-6.1.1-all`
> 
> `Windows 10`

您好，我的环境是
`gradle-6.4.1-all`
`macOS 10.15.4`
### 我这边好像跟一些权限有关，目前已经解决了不能创建文件夹的问题，但是会出现一个新的问题。
### 通过Build->Generate Signed Bundle / APK ->完成打包以后，命令都会强制在选项框里的文件夹内强制创立各个渠道无用文件夹。
### 比如代码里写的是`rootProject.file("/apk")`，理论上他会在根目录创建apk文件夹。但是选项框里比如是`根目录/app`那么最后打包的结果是，他会创建apk目录，但是同时也会在app里创建对应的渠道目录，这十分让人烦恼。gradle3.3对应的命令就不会出现这种问题。请问这个问题有什么办法屏蔽掉自动创建渠道文件夹呢？感觉gradle4.0自从删了outputScope这个属性以后，outputDirectory这个属性并不能覆盖掉系统那个选项框里默认的路径啊。不知道您对这个问题，有什么好的解决方案么。。。

**Comment by angcyo** [comment]
可以试一下:

`variant.getPackageApplication().outputDirectory = new File(project.rootDir.absolutePath + "/apk")`

通过`menu`打包`apk`, 确实会生成无用文件夹.(其实这个文件夹, 就是默认的`apk`输出路径, 只不过我们修改了`apk`的路径, 相当于把`apk`移走了. 但是文件夹还在...)

通过`task`打包`apk`, 不会出现上述问题.

> 推荐使用`assemble` `task`打包`apk`.

有时间, 我看下`gradle`源码, 看看能不能找到生成文件夹的代码. 伺机修改一下!

**Comment by liyuhaolol** [comment]
> 可以试一下:
> 
> `variant.getPackageApplication().outputDirectory = new File(project.rootDir.absolutePath + "/apk")`
> 
> 通过`menu`打包`apk`, 确实会生成无用文件夹.(其实这个文件夹, 就是默认的`apk`输出路径, 只不过我们修改了`apk`的路径, 相当于把`apk`移走了. 但是文件夹还在...)
> 
> 通过`task`打包`apk`, 不会出现上述问题.
> 
> > 推荐使用`assemble` `task`打包`apk`.
> 
> 有时间, 我看下`gradle`源码, 看看能不能找到生成文件夹的代码. 伺机修改一下!

嗯嗯，希望您看了源码后能给个完美的解决方案，谢谢
